### ISSUE TITLE
Didática e método de aula

### ISSUE THREAD

**Issue by kvnol** [openschoolbr/forum#10]
Não sei se isso entraria na estrutura, por isso criei uma issue para a didática e métodos de aula.

Um ponto essencial que eu imagino é: **zero palavrão/gírias** durante as aulas. É importante sermos o mais focados possível na hora de lecionar, pois pessoas de todas as idades e lugares vão assistir nossas aulas e utilizar palavrão ou gírias pode tirar o interesse da pessoa ou o foco da aula.

Isso é o que eu penso, mas quero saber de vocês.

**Comment by muniz95** [comment]
No repo [openschoolbr/sobre](https://github.com/openschoolbr/sobre) eu coloquei algumas regras e diretrizes a respeito.

**Comment by kvnol** [comment]
Ah maravilha, @muniz95, não tinha conseguido ler esse doc ainda, mas vi aqui. Perfeito. :heart:
