### ISSUE TITLE
all-contributors para reconhecer todos os contribuidores

### ISSUE THREAD

**Issue by gtkatakura** [openschoolbr/forum#11]
Creio que deveríamos criar uma maneira de reconhecer todos os contribuidores deste projeto, algumas pessoas podem contribuir com ideias incríveis, mas por não serem aqueles que colocam a mão na massa (commits - contributors do git), essa pessoa poderia ser esquecida pelo projeto e sua contribuição desmerecida porque não contribuiu diretamente ao repositório. Creio que o [all-contributors](https://github.com/kentcdodds/all-contributors) vá resolver justamente esse problema. Todos aqueles que contribuírem de uma forma significativa ao projeto deveriam ser reconhecidos.

**Comment by larismourullo** [comment]
Seria uma forma também de saber com quem você deve falar para resolver algum determinado problema como algum problema de design, você iria atrás de um contribuidor design não um desenvolvedor e coisas do tipo.

**Comment by kvnol** [comment]
Eu gosto bastante da ideia. Quer implementar, @gtkatakura? Não sei se entendi muito bem como a ferramenta funciona ou se é na mão. :smile:

**Comment by gtkatakura** [comment]
O uso é bem simples, basta possuir o nodejs na máquina. Posso implementar no repositório, só precisaria antes de uma lista dos contribuidores e quais emoji keys querem que eu coloque para cada um.

**Comment by gtkatakura** [comment]
Uso da ferramenta: https://www.npmjs.com/package/all-contributors-cli

**Comment by kvnol** [comment]
Creio eu que o único repositório que não necessitaria fosse o de **Fórum**, de restante acho totalmente válido. Sobre os contribuidores, teríamos que vasculhar as issues de cada repositório porque, até o momento, as maiores contribuições são de ideias e não PRs.

**Comment by larismourullo** [comment]
@gtkatakura ao qe vi teriamos que tirar alguns emojis como o financial, eventOrganizing, fundingFinding e quem sabe alterar eles para algo que fizesse mais sentido para nós, não sei.

**Comment by khaosdoctor** [comment]
@gtkatakura Isso foi sugerido no #14 e no #13 para termos um readme ou um arquivo que reconhecesse as pessoas e o que elas faziam :)

**Comment by khaosdoctor** [comment]
Vamos mover essa conversa para essas issues (a #14 mais especificamente sobre esse assunto) e ai vamos dar uma limpada na quantidade de issues que temos com o mesmo assunto :)
