### ISSUE TITLE
Diplomas e certificados

### ISSUE THREAD

**Issue by kvnol** [openschoolbr/forum#12]

**Comment by larismourullo** [comment]
Para ter algo como diploma e certificação precisaríamos de uma forma de regular se o usuário esta vendo os vídeos mesmo e se o mesmo fez todos os exercícios e afins, acredito que isso faria com que tivéssemos um login na página ou coisa do tipo e esse não é o foco. Não consigo pensar em outra forma para isso, se alguém soube por favor pronuncie-se.

**Comment by houstondapaz** [comment]
Acho que o proposito aqui é disseminar o conhecimento, certificados são provas para terceiros. Enfim não vejo pq emitir certificado... alem do mais, como a @larismourullo  falou teriamos que criar um mecanismo a mais q não é o foco

**Comment by larismourullo** [comment]
@houstondapaz esse mecanismo já tiraria o foco de ser algo ABERTO já que a pessoa teria que fazer conta no site, concordar com termos, e afins. Esse não é o foco.

**Comment by khaosdoctor** [comment]
@larismourullo Além de vídeos e outras coisas, temos uma outra parte para nos preocupar, como já estávamos falando no [tópico sobre o domínio](https://github.com/openschoolbr/openschoolbr.github.io/issues/4), para emitir um certificado ou um diploma é necessário que tenhamos um CNPJ, ai caímos em todas as coisas burocráticas que eu realmente não tenho a menor ideia de como funcionam kk

**Comment by kvnol** [comment]
Sim, abri a issue para uma discussão futura. Até linkando com a questão do registro do domínio.

**Comment by larismourullo** [comment]
@kvnol ao meu ver tem um CNPJ já iria contra o fato da escola ser aberta e de algo da comunidade em si. Pois a comunidade estar no nome e alguém 😢

**Comment by kivervinicius** [comment]
Certificados são interessantes para alunos provarem conhecimento para universidades, acredito que uma ONG consiga emitir certificados.

**Comment by khaosdoctor** [comment]
@larismourullo Ela pode ser aberta como organização sem fins lucrativos, ai não teria que estar necessariamente no nome de alguém (posso estar errado, nesse assunto sou muito leigo)

**Comment by kivervinicius** [comment]
@khaosdoctor Também sou leigo mas pelo que andei lendo, uma ong pode ter sim alguns registros que te proporcionam emitir certificados.

https://capitalsocial.cnt.br/tipos-de-registros-ongs-devem-ter/
```
> Receita Federal

Uma organização social para estar regular deverá se inscrever no Cadastro Nacional da Pessoa Jurídica (CNPJ). Isso é feito na Receita Federal.
```

Vamos pesquisar mais sobre isso.

**Comment by khaosdoctor** [comment]
Sim! @kivervinicius, mas vai ter que ter o nome de uma pessoa?

**Comment by kivervinicius** [comment]
@khaosdoctor Ainda estou pesquisando, o legal seria se conseguíssemos um contador para nos dar estas informações.

**Comment by larismourullo** [comment]
@khaosdoctor eu também sou leiga, nunca precisei criar nada do tipo, mas acredito que precise provar que a organização sem fins existe realmente, é um processo burocrático ao meu ver.

**Comment by khaosdoctor** [comment]
@larismourullo Isso com certeza :/ a burocracia mata muita coisa

**Comment by WendellAdriel** [comment]
Sobre certificados, se for um curso livre qualquer pessoa (até mesmo pessoa física) pode emitir um certificado.

Agora caso queira que o curso seja reconhecido por algum órgão, etc é mais complicado, mas no geral se for um curso livre não precisa de nada disso. Por exemplo pode emitir um certificado em nome da OpenSchool e assinado pelo(s) professor(es) do curso em questão.

**Comment by khaosdoctor** [comment]
Pessoal, eu acho que não vale muito discutirmos isso agora... Nem temos cursos prontos, vamos definir legal todas essas partes e de fato iniciar um curso para que possamos pensar como ele vai se desenrolar e como vamos nos organizar com eles, ai podemos saber o que vamos precisar e quais são as dificuldades que vamos enfrentar. 

**TL;DR**: Acho que estamos colocando a carroça na frente dos bois kk

**Comment by suissa** [comment]
@khaosdoctor concordo.
