### ISSUE TITLE
Cheatsheet de linguagens

### ISSUE THREAD

**Issue by houstondapaz** [openschoolbr/forum#15]
Estava aqui pensando nas diversas linguagens que podemos ensinar e, basicamente todas tem um padrão de sintaxe própria mas a lógica é a mesma.
Com isso pensei em criarmos uma cheatsheet com o de-para da sintaxe de cada linguagem, com If, for, foreach, while, função e todos os padrões que existem nas diversas linguagens.
Uma sheet para cada linguagem..
Deu para entender?

**Comment by larismourullo** [comment]
@houstondapaz um curso para mostrar como funciona em todas as linguagens o IF, ELSE e afins né? Gostei da ideia, acho isso legal pra galera que começa, para verem que o que muda só é sintaxe de resto é tudo igual. 👍

**Comment by kvnol** [comment]
@larismourullo acho que o @houstondapaz quis falar de um repositório com o cheatsheet e não um curso em si. No mais, eu acho a ideia bem foda e que teríamos contribuição de uma galera forte em diversas linguagens.

**Comment by kvnol** [comment]
@houstondapaz, tomei a liberdade de criar o repo: https://github.com/openschoolbr/cheatsheet :smile:

**Comment by houstondapaz** [comment]
Oi @larismourullo  o que quis falar é o que o @kvnol  disse rs. Termos um repo ou cada linguagem com a sua. Todos com uma estrutura basica. Talvez mais pra frente fazer uma pagina que faça um filtro por linguagem, com comparação e tudo mais... mas agora é pensar simples.
Um exemplo é essa do [jquery ](https://websitesetup.org/wp-content/uploads/2017/01/JQUERY-CHEAT-SHEET-a.png)(que é bem completa) mas não tem o depara q eu falei

**Comment by houstondapaz** [comment]
@kvnol  que rapido

**Comment by kvnol** [comment]
Acho que por enquanto conseguimos manter no repositório, se crescer muito migramos para uma página a parte.

**Comment by larismourullo** [comment]
@houstondapaz e @kvnol eu entendi que seria um repo pra isso, mas acho que fica legal também sair um vídeo sobre isso, como uma curiosidade pra galera.

**Comment by khaosdoctor** [comment]
Basicamente é uma tabela de equivalência entre linguagens, é uma ideia bem legal mesmo! Mas vai ser uma coisa bastante complexa de entender, até porque cada linguagem tem sua própria sintaxe, mas vamos iniciar, se vingar podemos continuar, se não paciencia haha

**Comment by khaosdoctor** [comment]
Como a cheatsheet foi criada já, eu vou fechar aqui :)
