### ISSUE TITLE
Ideia para o canal do youtube

### ISSUE THREAD

**Issue by larismourullo** [openschoolbr/forum#16]
Então pessoal, como havia mencionado no slack tive a ideia de passar outros conteúdos pra galera no nosso canal não sendo apenas vídeos de aulas e dos cursos. Poderíamos toda semana lançar algum vídeo curto, este sendo sobre alguma curiosidade, dicas (estas sendo voltadas pra galera que já trabalha na área ou quem ta começando) e por ai vai. Quem sabe até futuramente a gente lançar um podcast pra galera saber mais sobre a área, conhecer melhor os professores, divulgar os novos cursos, dizer quais conteúdos sairão, etc. O que vocês acham?

**Comment by houstondapaz** [comment]
Acho a ideia muito boa, afinal somos uma "escola" não um repositório de cursos rs.
Quanto mais formas tiver para disseminar conhecimento melhor.
