### ISSUE TITLE
Talks Periódicas (Hangout, YT)

### ISSUE THREAD

**Issue by russiann** [openschoolbr/forum#17]
O que acham de palestras em vídeos transmitidas via Hangouts periódicos ao vivo (posteriormente gravados no YT) feitos pela galera da comunidade?

- Os Hangouts seriam feitos por pessoas da comunidade.
- Receberíamos sugestões de assuntos abordados em issues do github
- Seria aberto um Call for Papers por ciclo para que a própria comunidade decidisse os assuntos da vez.
- O período dependeria de quantas aplicações foram feitas mas poderiam ser Semanal, Quinzenal ou Mensal. (eu prefiro no máximo quinzenal rs)
- As gravações poderiam ficar salvas em uma playlist dentro de um canal da organização (já idealizado na issue #16) 

O que acham da idéia? 😀

**Comment by larismourullo** [comment]
Concordo ❤️

**Comment by kvnol** [comment]
Eu gosto muito dessa ideia, também. <3

**Comment by bernardocs** [comment]
Botei fé! :)
Eu particularmente tenho tentado acompanhar tudão de uma vez e ta sendo hard... 😶  
Acho legal até como informativo do que tem sido discutido.

**Comment by lai32290** [comment]
> Acho legal até como informativo do que tem sido discutido

Gostei da ideia, eu também to sentindo o mesmo, é muita coisa pra acompanhar.

**Comment by russiann** [comment]
As palestras não precisam ser necessariamente grandes, em um dia pode haver um mix com uma Main Talk maior de 40\~80 minutos + dois Light Talks de 15\~30 minutos.
Os assuntos também não precisam ser necessariamente complexos, o importante é compartilhar.
E essas Talks são até mais fáceis de fazer do que um curso, por isso minha sugestão de ser periódicos.

**Comment by khaosdoctor** [comment]
Acho que primeiro podemos definir os cursos e depois voltar neste assunto o que acham?

**Comment by yuriploc** [comment]
É, tendo os cursos definidos facilita o processo de definir as Talks periódicas como parte de cada curso também.

**Comment by khaosdoctor** [comment]
Vou Fechar por enquanto então até o #2 ser definido
