### ISSUE TITLE
Curso - Estruturas de dados

### ISSUE THREAD

**Issue by rlage** [openschoolbr/forum#18]
- assunto principal do curso: Estruturas de dados
- nível do público alvo (básico-intermediário)
- ideal ter feito o curso de [lógica de programação](https://github.com/openschoolbr/curso-logica-programacao/issues/1)

Estou sugerindo aqui a criação do curso de estruturas de dados. Dependendo do tamanho e complexidade do curso, provavelmente seria interessante dividir em dois cursos, estruturas de dados 1 e 2. Mas inicialmente pensei em discutirmos os conteúdos.

Ementa:

1. Introdução
O que é um algoritmo, para que serve (seria uma recapitulação do curso de lógica)
Análise de complexidade de algoritmos

2. Algoritmos de ordenação
HeapSort, QuickSort, etc.

3. Estruturas de dados
Pilhas, filas, listas
Árvores de busca
Hash
Árvores AVL e Rubro-negra

4. Algoritmos avançados
Programação dinâmica
Algoritmos gulosos

5. Estruturas de dados avançadas
Árvores B
Fibonacci Heap

6. Algoritmos em grafos
Busca em largura, busca em altura
Algoritmos de caminho mais curto

7. Outros algoritmos
Programação linear
Algoritmos multithread
Problemas NP-Completos

Pessoal, sugiram alterações, adicionem coisas... na minha cabeça, 1,2,3 seriam os capítulos de estruturas de dados 1 e o restante de estruturas de dados 2. O "livro texto" seria o Introduction to Algorithms, do CRLS.

**Comment by bernardocs** [comment]
Dúvida: Análise de complexidade ciclomática cabe à este curso? 🤔 

Digo... não só a análise como a definição e a importância do mesmo.

**Comment by rlage** [comment]
@larismourullo Criado aqui. Por algum motivo, não consigo adicionar labels à issue... deve ser pq eu não faço parte da organização rs. Adiciona pra mim, por favor. Deveria ter as tags "curso" e "sugestão"

**Comment by larismourullo** [comment]
@rlage adicionado 👍

**Comment by rlage** [comment]
@bernardocs não tenho certeza... pq pelo que entendi, a complexidade ciclomática é a complexidade de um determinado sistema, não de um algoritmo em si. Talvez devesse entrar num curso de qualidade de software, que poderia ser mais amplo... posso estar errado tb, talvez alguém mais tenha uma opinião sobre isso...

**Comment by erandirjunior** [comment]
Complexidade ciclomática é algoritmos avançados.

**Comment by rlage** [comment]
@fsoaresjunior Complexidade ciclomática é uma métrica de software usada para indicar a complexidade de um programa de computador... por isso entendi como algo mais de qualidade, por causa das palavras "métrica" e "programa de computador". 

Além disso, pesquisei por aí e, em geral, esse conceito é apresentado aos alunos em disciplinas como engenharia de software e testes de software.

Dito isso, nada impede de colocarmos aqui, porém temos q ver se não seria melhor em outro lugar.

**Comment by rlage** [comment]
Ou talvez um curso separado sobre complexidade de algoritmos... onde poderíamos apresentar várias notações e métodos mais a fundo. E aqui apresentaríamos apenas a mais comum, que é a big-o notation, pq é importante para entender as otimizações (muitas explicações de algoritmos passam pela justificativa de ter menor complexidade, considerando essa notação).

**Comment by houstondapaz** [comment]
Acho que complexidade ciclomatica algo bem avançado, cabe em algo sobre qualidade de software msm

**Comment by erandirjunior** [comment]
eu colocaria complexidade ciclomática em um conteúdo mais avançado, assim como ordenação, busca.

**Comment by rlage** [comment]
@fsoaresjunior , como o @houstondapaz falou, qualidade de software é um conteúdo mais avançado, vc geralmente vê depois de saber fazer esses algoritmos aqui. Lembrando que, embora sejam algoritmos avançados, vc cursa no terceiro ou quarto periodo da faculdade. Qualidade de software (e análise de algoritmos) vc cursa mais para o final, geralmente, no quinto ou sexto. Talvez devêssemos ter uma matéria de análise de algoritmos e colocar complexidade ciclomática lá. O que acham?

**Comment by bernardocs** [comment]
Na real, complexidade ciclomática é uma métrica que quantifica, basicamente, a quantidade de desvios de fluxo (if's) que um determinado módulo possui.
(é um pouco mais do que isso... mas enfim...)

Posso não ter sido claro apenas... :X
Eu sempre coloquei isso no mesmo campo de complexidade computacional (Big O notation) mas creio, realmente, ser relacionado à qualidade de software. :parrot:

**Comment by rlage** [comment]
Então, @bernardocs , eu não vi complexidade ciclomática em análise de algoritmos. Sendo totalmente sincero, eu não vi isso na faculdade (ou não me lembro rs). Então dei uma pesquisada, busquei entender o mínimo e tive o mesmo entendimento que vc, acerca do fluxo de if's, e vi isso relacionado á qualidade de software e testes. A Big O notation é diferente, basicamente ela olha apenas para um algoritmo e, principalmente, a quantidade de repetições do código... a grosso modo, tb não sou nenhum expert em complexidade de algoritmos.

**Comment by lflimeira** [comment]
Galera, não seria melhor, issues como essa serem discutidas no Slack? Dessa forma, quando fechasse uma galera para fazer o curso, ai o repositório é criado pelos organizadores e essas issues seriam criadas nos repositórios de cada curso.

**Comment by rlage** [comment]
pode ser @lflimeira ... tem o canal la no slack já, vou passar para la a ementa e a gente vai discutindo

**Comment by lflimeira** [comment]
Pode fechar essa issue então?

**Comment by rlage** [comment]
Vamos continuar a discussão no slack. Fechando a issue aqui.
