### ISSUE TITLE
Processo para se tornar colaborador : Discussão

### ISSUE THREAD

**Issue by rlage** [openschoolbr/forum#21]
Antes de tudo, leia as responsabilidades do(a) Colaborador(a) e veja se está de acordo com isso. Em seguida leia toda essa sessão de como se tornar colaborador (a).

Basicamente você só precisa abrir um pull request nesse repositório adicionando seu perfil com os dados necessários conforme esse nosso [template](colaborador_template.md). Lembre-se que o nome do arquivo deve ser seu nome e sobrenome ou seu usuário do GitHub com a extensão .md. Também precisa alterar a nossa lista de colaboradores(as) com o link para esse novo arquivo conforme os demais.

Após feito o Pull Request contendo os dois arquivos alterados (seu perfil de colaborador(a) e o arquivo com a lista de colaboradores(as), você será avaliado(a) pelos(as) outros mentores(as) do projeto antes de poder participar, levando em conta sua experiência, perfil interpessoal, dentre outros pontos. Porém não tenha medo, nossos maiores critérios são sua vontade de ajudar, como trata outras pessoas e disponibilidade.

## Resumindo

1. Você abre um PR
2. Os organizadores(as) avaliam seu perfil
3. Se seu perfil for aprovado, você vira colaborador(a) e é convidado a entrar no Slack de colaboradores
4. Dependendo do tipo de área que você deseja atuar, entre em contato com o responsável para saber como ajudar. Se você irá realizar uma nova iniciativa (um novo curso, por exemplo) entre em contato com os organizadores.

Caso você tenha alguma dúvida nesse processo, crie uma issue neste repositório.

-------------------

Sugestões de alteração, escrita, etc., manda ver ai embaixo.

**Comment by kvnol** [comment]
@rlage Curti, mas será que não seria melhor colocar isso no Sobre da Open School? Assim como o código de conduta, @muniz95. Acho que o fórum tem que conter só as mesmo, não arquivos deste tipo.

**Comment by rlage** [comment]
@kvnol certamente... vou colocar o arquivo do template lá, mas acho q a discussão do processo estar aqui no forum faz sentido... qdo estiver pronta, faço um PR la no sobre... ou já faço um PR lá no sobre, com os dois arquivos e a galera discute no próprio PR?

**Comment by rlage** [comment]
Criei lá, @kvnol https://github.com/openschoolbr/sobre/pull/7

**Comment by rlage** [comment]
Agora é discutir aqui se esse processo e o template do PR fazem sentido, o que precisamos mudar, etc.

**Comment by khaosdoctor** [comment]
Eu gosto do processo de abrir uma PR direto, temos que colocar no "sobre" já como deve ser feito e também definir o core team do projeto que nem foi referenciado no #13 e #14, para o pessoal saber a quem recorrer. Acho que isso é a prioridade inicial

**Comment by rlage** [comment]
Concordo @khaosdoctor , criei outro PR para isso https://github.com/openschoolbr/sobre/pull/8

**Comment by houstondapaz** [comment]
Tb estou de acordo com o processo de PR, só acho que precisa alterar um pouco o texto, essa parte "você será avaliado(a) pelos(as) outros mentores(as) do projeto" pode assustar bastante

**Comment by alinebastos** [comment]
Mas no Training Center, por exemplo, tem essa fase de ser avaliados pelos outros mentores, e sempre foi de boa.

**Comment by houstondapaz** [comment]
Sim, não to falando que não precise dessa fase, mas eu lendo dei aquele pé pra tras... mas talvez seja uma boa dar esse "choque" de realidade hahaha

**Comment by khaosdoctor** [comment]
Eu acho que é importante, @houstondapaz porque a pessoa que vai se aplicar vai saber que **existem** pessoas empenhadas por trás que estão tomando conta do projeto, que ele não está abandonado e nem sem cuidados 😄 

Já dá uma noção de ordem

**Comment by khaosdoctor** [comment]
Isso está sendo discutido na https://github.com/openschoolbr/sobre/pull/8/
