### ISSUE TITLE
Identidade visual da Open School Brasil

### ISSUE THREAD

**Issue by kvnol** [openschoolbr/forum#3]
Galera, como essa comunidade é open-source, abrimos essa issue para a votação e decisão da identidade visual da **Open School Brasil** e seria maravilhoso se uma galera boa participasse (para criar propostas e votar) nas melhores ideias de logotipos, assim como estamos fazendo no [Front-end Brasil](https://github.com/frontendbr/sugestoes/issues/20). Para isso acontecer da melhor forma, segue:

## Algumas dicas para construção da proposta

Alguns conceitos que seriam interessantíssimos de nós (designers, ou não, que estamos fazendo propostas) tentarmos seguirmos é:

1. Representar e ter como conceito a ideia do **open source** e **conhecimento/aprendizado**
2. Como a marca será open-source, somos uma comunidade open-source, é obrigatório (a não ser que alguém compre - não sei se seria interessante) trabalharmos com fontes open-source: https://fonts.google.com/
3. Pense nas diferentes aplicações que podemos fazer no futuro com a marca: stickers, camisetas, impressos - por isso, aplique o logo em diferentes fundos, teste-o em cores monocromáticas e teste a aplicação apenas com o símbolo (no caso de um favicon, por exemplo) ou lettering.

Obs.: Antes de criar qualquer coisa lembre-se que **somos uma comunidade open-source**, por isso críticas construtivas serão feitas para uma melhor identidade para a organização. Não emocione-se em demasia, defenda seus pontos sem ofender os demais. :heart:

**Comment by woliveiras** [comment]
Depois é interessante criar um esquema desse, @kvnol:

https://github.com/training-center/brand-guide

**Comment by kvnol** [comment]
Sim, @woliveiras. Com certeza! :heart:

**Comment by khaosdoctor** [comment]
Acho que precisamos tanto criar um brand guide quanto sugestões de logos, tipo o issue do frontendbr com a nova identidade visual (acho que o @kvnol estava participando nesse ai) ai podemos chamar a galera lá para tentar dar uma ajuda, porque eu até sei fazer o design, eu só não sou criativo o suficiente kkkk

**Comment by kvnol** [comment]
@khaosdoctor farei exatamente isso, mano. hahahaha, da mesma forma que elaborei no Front-end Brasil. :smile:

**Comment by kvnol** [comment]
Posso dar o pontapé inicial nas propostas?

Minhas madrugadas são muito criativas (pena que no outro dia, para acordar, é uma merda) por isso fiquei até tarde rabiscando.

## Aplicação vertical
![openschool-1](https://user-images.githubusercontent.com/3299130/28906725-d26f8cf4-77ef-11e7-8324-dbdc95fba8b2.png)
![openschool-2](https://user-images.githubusercontent.com/3299130/28906726-d2707560-77ef-11e7-982c-ded1c2ecf781.png)
![openschool-3](https://user-images.githubusercontent.com/3299130/28906724-d26b266e-77ef-11e7-97de-701474825e1d.png)

## Aplicação horizontal
![openschool-horizontal-1](https://user-images.githubusercontent.com/3299130/28906732-d72800c8-77ef-11e7-8c0a-1e5b27a52fd3.png)
![openschool-horizontal-2](https://user-images.githubusercontent.com/3299130/28906733-d7294ff0-77ef-11e7-90da-f26147add5fb.png)
![openschool-horizontal-3](https://user-images.githubusercontent.com/3299130/28906731-d72705ce-77ef-11e7-9f87-55814d52fc48.png)

# Conceito
Com base nas dicas que eu mesmo (que coisa) [coloquei aqui na issue](https://github.com/openschoolbr/forum/issues/3#issue-247461178), tive a ideia de uma porta significar o nosso "open" da marca (que representa o **open source**, uma sugestão do @rubenmarcus :clap:) com linhas de código representando a **programação** que será o principal propósito da escola.

E alguns pontos mais simples:
- Utilizei a fonte [Open Sans](https://fonts.google.com/specimen/Open+Sans) para fazer um trocadilho com o nome da escola;
- A cor roxa (#72009d) foi utilizada para dar um toque jovial à marca, com elegância, e transmitindo a inspiração para os estudos;
- O "Brasil" não foi o maior destaque, pois pensei num crescimento dessa marca podendo atingir outros países (o que seria maravilhoso).

That's all, folks. :heart:

**Comment by alinebastos** [comment]
Nossa, tá lindo!!! E muito bem pensado :)

**Comment by lflimeira** [comment]
Eu curti em :smile:

**Comment by khaosdoctor** [comment]
Gostei hein :o

**Comment by muniz95** [comment]
Ficou 11/10, muito bom mesmo!!

**Comment by jeffersondanielss** [comment]
@kvnol isso ficou muito massa!

**Comment by woliveiras** [comment]
@kvnol mandou muuuuuito bem mano! 
Caracos!

**Comment by juulhao** [comment]
Caralho vocês são do mal! amei !!

**Comment by muniz95** [comment]
Por mim essa é a versão final, ta aprovadíssima!

**Comment by kvnol** [comment]
Estava esperando outras sugestões, mas como todos gostaram... :smile:  Ainda tenho alguns ajustes para fazer no lettering e tal, que reparei agora.

Alguém mais vai enviar sugestões? Se alguém estiver para fazer ou fazendo, manda um comentário para os admins não definirem ainda. :open_mouth:

ps: @openschoolbr/admins, de qualquer forma, me proponho para ficar responsável pelo design do rolê todo da escola. Se quiserem me colocar na org, vou criando o repositório **/design**. :heart:

**Comment by alinebastos** [comment]
Os admins somos todos nós :)

**Comment by kvnol** [comment]
Então vam'bora.

**Comment by khaosdoctor** [comment]
Aprovo o @kvnol como designer hahaha o cara manda muito

**Comment by khaosdoctor** [comment]
@kvnol cara, cria um repo de brand guide ai pra gente saber das coisas da marca e tal e ai coloca tudo dentro :) acho que fica mais simples pra todo mundo

**Comment by kvnol** [comment]
@khaosdoctor então, vou criar um repositório pra brand, mas queria colocar dentro do openschoolbr direto (regras de uso e tal, pq a aplicação na org não ficou boa #chato). Fica melhor que forkar, me coloca como adm que crio tudo. :smile:

**Comment by lflimeira** [comment]
@kvnol eu mandei a solicitação para vc.

**Comment by kvnol** [comment]
Maravilha. Então pra coisas relacionadas ao design da marca podemos nos encontrar no: https://github.com/openschoolbr/design :heart: 

Já falei que vocês são bonitinhos, né? :smile:

**Comment by larismourullo** [comment]
ADOREI! :heart:

**Comment by nandomoreirame** [comment]
ficou S E N S A C I O N A L :heart:

**Comment by adeonir** [comment]
@kvnol a ideia ficou ótima. Muito bom!

O detalhe das linhas, eu vi que remetiam ao código somente depois de ler a issue.
À primeira vista, parece uma régua, com as marcações das medidas.
Mass, isso pode ter sido somente a minha impressão.
