### ISSUE TITLE
Registro do domínio

### ISSUE THREAD

**Issue by kvnol** [openschoolbr/forum#4]
Galera, quando o @rubenmarcus fez a sugestão do nome para ver se o domínio estava disponível e achei essa domínio que seria ótimo para padronizarmos a marca: **org.br**. O que acham?

![image](https://user-images.githubusercontent.com/3299130/28926090-2a188882-783d-11e7-8f43-8cc2867ddd8a.png)

**Comment by muniz95** [comment]
@kvnol show de bola. Só não sei como faríamos com essa questão de comprovar que somos uma ONG de fato, não tenho experiência com isso 😕

**Comment by khaosdoctor** [comment]
Tem que ter um CNPJ que comprove, é uma coisa meio chata... Mas eu acho que o @woliveiras teve esse problema no ABCDev que tem o domínio .org também

**Comment by kvnol** [comment]
This issue was moved to openschoolbr/openschoolbr.github.io#4
