### ISSUE TITLE
Grupo no Telegram

### ISSUE THREAD

**Issue by muniz95** [openschoolbr/forum#7]
Galera, criei um grupo no Telegram, está aberto a todos, segue o [link](https://t.me/openschoolbr)

Futuramente podem rolar algumas integrações, bots, etc hehe

**Comment by nandomoreirame** [comment]
:+1:

**Comment by carloshenriqueribeiro** [comment]
Acho que já podemos fechar essa issue, não ?

**Comment by houstondapaz** [comment]
Vamos descontinuar o grupo do telegram certo? Mudar todo mundo pro slack

**Comment by carloshenriqueribeiro** [comment]
Melhor coisa!

Carlos Ribeiro

Em 5 de ago de 2017 11:51 PM, "Houston da Paz" <notifications@github.com>
escreveu:

**Comment by muniz95** [comment]
Vou fixar uma mensagem indicando que nosso canal oficial passou a ser o slack, e que todas as sugestões e questionamentos devem ser feitos por lá.

Manterei ele ativo pra testar integrações com o GitHub e outros serviços que utilizaremos.
