### ISSUE TITLE
Nossas redes sociais

### ISSUE THREAD

**Issue by kvnol** [openschoolbr/forum#8]
Onde a Open School irá atuar, creio que as melhores frentes sejam o YouTube, Facebook e Twitter (nessa sequência de prioridade).

A página no Facebook eu criei: https://www.facebook.com/openschoolbr/

Estou montando o Twitter e o YouTube, em breve conversamos sobre as localizações das senhas e quem ficará responsável pela criação de conteúdo e moderação das nossas redes.

**Comment by muniz95** [comment]
Um membro do grupo no Telegram (creio que o @yuriploc) criou um canal no Slack também: https://join.slack.com/t/openschoolbr/shared_invite/MjIyODQxMzI3MzM0LTE1MDE3OTIwMjktNDQwMWUxNmYwZQ

**Comment by nandomoreirame** [comment]
Wow :tada:

**Comment by kvnol** [comment]
Twitter: https://twitter.com/openschoolbr/
YouTube: https://www.youtube.com/channel/UCjKrg9qAUZ7Iv6EgaxZ0YUg

**Comment by anony000** [comment]
Seria uma boa ter um canal no Slack também :/

**Comment by kvnol** [comment]
@anony000, estamos no Slack. O @muniz95 postou o link comentários acima:

> Um membro do grupo no Telegram (creio que o @yuriploc) criou um canal no Slack também: https://join.slack.com/t/openschoolbr/shared_invite/MjIyODQxMzI3MzM0LTE1MDE3OTIwMjktNDQwMWUxNmYwZQ

**Comment by kvnol** [comment]
E uma atualização, nosso Medium está no ar: https://medium.com/openschoolbr/ ♥

**Comment by anony000** [comment]
Perdão, não havia visto hehe
